/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SureWorkEscrow {
  export type GigStruct = {
    gigId: BigNumberish;
    client: AddressLike;
    freelancer: AddressLike;
    paymentToken: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    metadataURI: string;
    createdAt: BigNumberish;
    fundedAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type GigStructOutput = [
    gigId: bigint,
    client: string,
    freelancer: string,
    paymentToken: string,
    amount: bigint,
    deadline: bigint,
    status: bigint,
    metadataURI: string,
    createdAt: bigint,
    fundedAt: bigint,
    completedAt: bigint
  ] & {
    gigId: bigint;
    client: string;
    freelancer: string;
    paymentToken: string;
    amount: bigint;
    deadline: bigint;
    status: bigint;
    metadataURI: string;
    createdAt: bigint;
    fundedAt: bigint;
    completedAt: bigint;
  };
}

export interface SureWorkEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "ARBITER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "approveWork"
      | "cancelGig"
      | "clientGigs"
      | "createGig"
      | "feeCollector"
      | "freelancerGigs"
      | "fundGig"
      | "getClientGigs"
      | "getFreelancerGigs"
      | "getGig"
      | "getRoleAdmin"
      | "gigs"
      | "grantRole"
      | "hasRole"
      | "platformFeePercent"
      | "raiseDispute"
      | "renounceRole"
      | "resolveDispute"
      | "revokeRole"
      | "setFeeCollector"
      | "setPlatformFee"
      | "submitWork"
      | "supportsInterface"
      | "totalFeesCollected"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResolved"
      | "GigCancelled"
      | "GigCompleted"
      | "GigCreated"
      | "GigDisputed"
      | "GigFunded"
      | "PlatformFeeUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "WorkSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ARBITER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveWork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelGig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clientGigs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createGig",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "freelancerGigs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundGig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClientGigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFreelancerGigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "gigs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ARBITER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveWork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelGig", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clientGigs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freelancerGigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundGig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClientGigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFreelancerGigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gigs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    gigId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gigId: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    gigId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GigCancelledEvent {
  export type InputTuple = [gigId: BigNumberish];
  export type OutputTuple = [gigId: bigint];
  export interface OutputObject {
    gigId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GigCompletedEvent {
  export type InputTuple = [
    gigId: BigNumberish,
    amountPaid: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [gigId: bigint, amountPaid: bigint, fee: bigint];
  export interface OutputObject {
    gigId: bigint;
    amountPaid: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GigCreatedEvent {
  export type InputTuple = [
    gigId: BigNumberish,
    client: AddressLike,
    freelancer: AddressLike,
    amount: BigNumberish,
    paymentToken: AddressLike
  ];
  export type OutputTuple = [
    gigId: bigint,
    client: string,
    freelancer: string,
    amount: bigint,
    paymentToken: string
  ];
  export interface OutputObject {
    gigId: bigint;
    client: string;
    freelancer: string;
    amount: bigint;
    paymentToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GigDisputedEvent {
  export type InputTuple = [gigId: BigNumberish, initiator: AddressLike];
  export type OutputTuple = [gigId: bigint, initiator: string];
  export interface OutputObject {
    gigId: bigint;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GigFundedEvent {
  export type InputTuple = [gigId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [gigId: bigint, amount: bigint];
  export interface OutputObject {
    gigId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeePercent: BigNumberish];
  export type OutputTuple = [newFeePercent: bigint];
  export interface OutputObject {
    newFeePercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [gigId: BigNumberish, freelancer: AddressLike];
  export type OutputTuple = [gigId: bigint, freelancer: string];
  export interface OutputObject {
    gigId: bigint;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SureWorkEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): SureWorkEscrow;
  waitForDeployment(): Promise<this>;

  interface: SureWorkEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ARBITER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  approveWork: TypedContractMethod<
    [_gigId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelGig: TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;

  clientGigs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  createGig: TypedContractMethod<
    [
      _freelancer: AddressLike,
      _paymentToken: AddressLike,
      _amount: BigNumberish,
      _deadline: BigNumberish,
      _metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  freelancerGigs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  fundGig: TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;

  getClientGigs: TypedContractMethod<
    [_client: AddressLike],
    [bigint[]],
    "view"
  >;

  getFreelancerGigs: TypedContractMethod<
    [_freelancer: AddressLike],
    [bigint[]],
    "view"
  >;

  getGig: TypedContractMethod<
    [_gigId: BigNumberish],
    [SureWorkEscrow.GigStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  gigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        gigId: bigint;
        client: string;
        freelancer: string;
        paymentToken: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        metadataURI: string;
        createdAt: bigint;
        fundedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  raiseDispute: TypedContractMethod<
    [_gigId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [_gigId: BigNumberish, _winner: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeCollector: TypedContractMethod<
    [_newFeeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ARBITER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveWork"
  ): TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelGig"
  ): TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clientGigs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createGig"
  ): TypedContractMethod<
    [
      _freelancer: AddressLike,
      _paymentToken: AddressLike,
      _amount: BigNumberish,
      _deadline: BigNumberish,
      _metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "freelancerGigs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundGig"
  ): TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClientGigs"
  ): TypedContractMethod<[_client: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getFreelancerGigs"
  ): TypedContractMethod<[_freelancer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getGig"
  ): TypedContractMethod<
    [_gigId: BigNumberish],
    [SureWorkEscrow.GigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "gigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        gigId: bigint;
        client: string;
        freelancer: string;
        paymentToken: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        metadataURI: string;
        createdAt: bigint;
        fundedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [_gigId: BigNumberish, _winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_newFeeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<[_gigId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "GigCancelled"
  ): TypedContractEvent<
    GigCancelledEvent.InputTuple,
    GigCancelledEvent.OutputTuple,
    GigCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GigCompleted"
  ): TypedContractEvent<
    GigCompletedEvent.InputTuple,
    GigCompletedEvent.OutputTuple,
    GigCompletedEvent.OutputObject
  >;
  getEvent(
    key: "GigCreated"
  ): TypedContractEvent<
    GigCreatedEvent.InputTuple,
    GigCreatedEvent.OutputTuple,
    GigCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GigDisputed"
  ): TypedContractEvent<
    GigDisputedEvent.InputTuple,
    GigDisputedEvent.OutputTuple,
    GigDisputedEvent.OutputObject
  >;
  getEvent(
    key: "GigFunded"
  ): TypedContractEvent<
    GigFundedEvent.InputTuple,
    GigFundedEvent.OutputTuple,
    GigFundedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;

  filters: {
    "DisputeResolved(uint256,address,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "GigCancelled(uint256)": TypedContractEvent<
      GigCancelledEvent.InputTuple,
      GigCancelledEvent.OutputTuple,
      GigCancelledEvent.OutputObject
    >;
    GigCancelled: TypedContractEvent<
      GigCancelledEvent.InputTuple,
      GigCancelledEvent.OutputTuple,
      GigCancelledEvent.OutputObject
    >;

    "GigCompleted(uint256,uint256,uint256)": TypedContractEvent<
      GigCompletedEvent.InputTuple,
      GigCompletedEvent.OutputTuple,
      GigCompletedEvent.OutputObject
    >;
    GigCompleted: TypedContractEvent<
      GigCompletedEvent.InputTuple,
      GigCompletedEvent.OutputTuple,
      GigCompletedEvent.OutputObject
    >;

    "GigCreated(uint256,address,address,uint256,address)": TypedContractEvent<
      GigCreatedEvent.InputTuple,
      GigCreatedEvent.OutputTuple,
      GigCreatedEvent.OutputObject
    >;
    GigCreated: TypedContractEvent<
      GigCreatedEvent.InputTuple,
      GigCreatedEvent.OutputTuple,
      GigCreatedEvent.OutputObject
    >;

    "GigDisputed(uint256,address)": TypedContractEvent<
      GigDisputedEvent.InputTuple,
      GigDisputedEvent.OutputTuple,
      GigDisputedEvent.OutputObject
    >;
    GigDisputed: TypedContractEvent<
      GigDisputedEvent.InputTuple,
      GigDisputedEvent.OutputTuple,
      GigDisputedEvent.OutputObject
    >;

    "GigFunded(uint256,uint256)": TypedContractEvent<
      GigFundedEvent.InputTuple,
      GigFundedEvent.OutputTuple,
      GigFundedEvent.OutputObject
    >;
    GigFunded: TypedContractEvent<
      GigFundedEvent.InputTuple,
      GigFundedEvent.OutputTuple,
      GigFundedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "WorkSubmitted(uint256,address)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
  };
}
